### Generate Dataset for Clothes Classifier

In [1]:
import csv
import os
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path

from random import uniform
from ultralytics import YOLO

In [2]:
# Path to your dataset root folder (contains category subfolders)
dataset_root = Path("../Clothes_Dataset").resolve()

if not dataset_root.exists():
    raise FileNotFoundError(f"Dataset folder not found: {dataset_root}")

print(f"Using dataset folder: {dataset_root}")

Using dataset folder: D:\VMGP\monash\2026 unihack\Clothes_Dataset

In [3]:
# Scan subfolders and collect image file records
allowed_ext = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
records = []

for category_dir in sorted(dataset_root.iterdir()):
    if category_dir.is_dir():
        for image_path in sorted(category_dir.iterdir()):
            if image_path.is_file() and image_path.suffix.lower() in allowed_ext:
                records.append(
                    {
                        "category": category_dir.name,
                        "image_path": str(image_path.resolve()),
                        "filename": image_path.name,
                    }
                )

df = pd.DataFrame(records)
print(f"Total images found: {len(df)}")
print(f"Categories found: {df['category'].nunique() if not df.empty else 0}")
df.head()

Total images found: 7000
Categories found: 14

,category,image_path,filename
0,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,001912_280188340_thumbnail_progressive_thumbna...
1,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,002800_158897544_thumbnail_progressive_thumbna...
2,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,00342aff-ba69-4cf2-ae62-e00680e9547a.jpg
3,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,00b8048d-635e-4e56-b182-071fb24eea32.jpg
4,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,010805_191610748_thumbnail_progressive_thumbna...

In [4]:
# Export to CSV and read it back as a DataFrame
csv_path = Path("clothes_dataset_index.csv").resolve()
df.to_csv(csv_path, index=False)
print(f"CSV exported to: {csv_path}")

CSV exported to: D:\VMGP\monash\2026 unihack\TayUnihack2026\clothes_dataset_index.csv

In [5]:
df = pd.read_csv(csv_path)
df.head()

,category,image_path,filename
0,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,001912_280188340_thumbnail_progressive_thumbna...
1,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,002800_158897544_thumbnail_progressive_thumbna...
2,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,00342aff-ba69-4cf2-ae62-e00680e9547a.jpg
3,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,00b8048d-635e-4e56-b182-071fb24eea32.jpg
4,Blazer,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Bl...,010805_191610748_thumbnail_progressive_thumbna...

### Generate Dataset for Color Classifier