In [13]:
import csv
import os
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path

from random import uniform

### Generate Dataset for Color Classifier

In [14]:
# Path to your dataset root folder (contains category subfolders)
color_dataset_root = Path("../Color_Dataset").resolve()

if not color_dataset_root.exists():
    raise FileNotFoundError(f"Dataset folder not found: {color_dataset_root}")
print(f"Using dataset folder: {color_dataset_root}")

Using dataset folder: D:\VMGP\monash\2026 unihack\Color_Dataset

In [15]:
# Scan subfolders and collect image file records
allowed_ext = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
records = []

for category_dir in color_dataset_root.iterdir():
    if category_dir.is_dir():
        for img_file in category_dir.iterdir():
            if img_file.is_file() and img_file.suffix.lower() in allowed_ext:
                records.append(
                    {
                        "color": category_dir.name.lower().removeprefix("mask_"),
                        "image_path": str(img_file.resolve()),
                        "filename": img_file.name,
                    }
                )

df = pd.DataFrame(records)
print(f"Total images found: {len(df)}")
print(f"Colors found: {df['color'].nunique() if not df.empty else 0}")
df.head()

Total images found: 465
Colors found: 9

   color                                         image_path    filename
0  black  D:\VMGP\monash\2026 unihack\Color_Dataset\Blac...  0a0502.png
1  black  D:\VMGP\monash\2026 unihack\Color_Dataset\Blac...       1.jpg
2  black  D:\VMGP\monash\2026 unihack\Color_Dataset\Blac...      10.jpg
3  black  D:\VMGP\monash\2026 unihack\Color_Dataset\Blac...      11.jpg
4  black  D:\VMGP\monash\2026 unihack\Color_Dataset\Blac...  110011.png

In [16]:
# Export to CSV and read it back as a DataFrame
color_csv_path = Path("color_dataset_index.csv").resolve()
df.to_csv(color_csv_path, index=False)
print(f"CSV exported to: {color_csv_path}")

CSV exported to: D:\VMGP\monash\2026 unihack\TayUnihack2026\color_dataset_index.csv

### Generate Dataset for Clothes Classifier

In [17]:
import csv
import os
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path

from random import uniform
from ultralytics import YOLO

In [18]:
# Path to your dataset root folder (contains category subfolders)
clothes_dataset_root = Path("../Clothes_Dataset").resolve()

if not clothes_dataset_root.exists():
    raise FileNotFoundError(f"Dataset folder not found: {clothes_dataset_root}")

print(f"Using dataset folder: {clothes_dataset_root}")

Using dataset folder: D:\VMGP\monash\2026 unihack\Clothes_Dataset

In [19]:
# Scan subfolders and collect image file records
allowed_ext = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
records = []

for category_dir in sorted(clothes_dataset_root.iterdir()):
    if category_dir.is_dir():
        for image_path in sorted(category_dir.iterdir()):
            if image_path.is_file() and image_path.suffix.lower() in allowed_ext:
                records.append(
                    {
                        "category": category_dir.name,
                        "image_path": str(image_path.resolve()),
                        "filename": image_path.name,
                    }
                )

df = pd.DataFrame(records)
print(f"Total images found: {len(df)}")
print(f"Categories found: {df['category'].nunique() if not df.empty else 0}")
df.head()

Total images found: 7391
Categories found: 10

,category,image_path,filename
0,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,001912_280188340_thumbnail_progressive_thumbna...
1,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,002800_158897544_thumbnail_progressive_thumbna...
2,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,00342aff-ba69-4cf2-ae62-e00680e9547a.jpg
3,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,00b8048d-635e-4e56-b182-071fb24eea32.jpg
4,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,010805_191610748_thumbnail_progressive_thumbna...

In [20]:
# Export to CSV and read it back as a DataFrame
clothes_csv_path = Path("clothes_dataset_index.csv").resolve()
df.to_csv(clothes_csv_path, index=False)
print(f"CSV exported to: {clothes_csv_path}")

CSV exported to: D:\VMGP\monash\2026 unihack\TayUnihack2026\clothes_dataset_index.csv

In [21]:
clothes_df = pd.read_csv(clothes_csv_path)
clothes_df.head()

,category,image_path,filename
0,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,001912_280188340_thumbnail_progressive_thumbna...
1,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,002800_158897544_thumbnail_progressive_thumbna...
2,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,00342aff-ba69-4cf2-ae62-e00680e9547a.jpg
3,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,00b8048d-635e-4e56-b182-071fb24eea32.jpg
4,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,010805_191610748_thumbnail_progressive_thumbna...

In [22]:
# Path to your dataset root folder (contains category subfolders)
clothes_dataset_root = Path("../Clothes_Dataset").resolve()

if not clothes_dataset_root.exists():
    raise FileNotFoundError(f"Dataset folder not found: {clothes_dataset_root}")

print(f"Using dataset folder: {clothes_dataset_root}")

Using dataset folder: D:\VMGP\monash\2026 unihack\Clothes_Dataset

In [23]:
# Scan subfolders and collect image file records
allowed_ext = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
records = []

for category_dir in sorted(clothes_dataset_root.iterdir()):
    if category_dir.is_dir():
        for image_path in sorted(category_dir.iterdir()):
            if image_path.is_file() and image_path.suffix.lower() in allowed_ext:
                records.append(
                    {
                        "category": category_dir.name,
                        "image_path": str(image_path.resolve()),
                        "filename": image_path.name,
                    }
                )
df = pd.DataFrame(records)
print(f"Total images found: {len(df)}")
print(f"Categories found: {df['category'].nunique() if not df.empty else 0}")
df.head()

Total images found: 7391
Categories found: 10

,category,image_path,filename
0,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,001912_280188340_thumbnail_progressive_thumbna...
1,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,002800_158897544_thumbnail_progressive_thumbna...
2,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,00342aff-ba69-4cf2-ae62-e00680e9547a.jpg
3,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,00b8048d-635e-4e56-b182-071fb24eea32.jpg
4,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,010805_191610748_thumbnail_progressive_thumbna...

In [24]:
# Export to CSV and read it back as a DataFrame
clothes_csv_path = Path("clothes_dataset_index.csv").resolve()
df.to_csv(clothes_csv_path, index=False)
print(f"CSV exported to: {clothes_csv_path}")
clothes_df = pd.read_csv(clothes_csv_path)
clothes_df.head()

CSV exported to: D:\VMGP\monash\2026 unihack\TayUnihack2026\clothes_dataset_index.csv

,category,image_path,filename
0,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,001912_280188340_thumbnail_progressive_thumbna...
1,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,002800_158897544_thumbnail_progressive_thumbna...
2,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,00342aff-ba69-4cf2-ae62-e00680e9547a.jpg
3,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,00b8048d-635e-4e56-b182-071fb24eea32.jpg
4,Coat,D:\VMGP\monash\2026 unihack\Clothes_Dataset\Co...,010805_191610748_thumbnail_progressive_thumbna...